Program Cuu_chuong_1;
Var
	so :Integer;

Begin
   Write('-Bang cuu chuong so may ?: ');
	Readln(so);
	Writeln;
   Writeln;
   Writeln(' CHUONG TRINH BANG CUU CHUONG');
   Writeln('-------------------------------');
   Writeln;
   Writeln(so:2,' lan  1  = ',so*1:3);
	Writeln(so:2,' lan  2  = ',so*2:3);
   Writeln(so:2,' lan  3  = ',so*3:3);
   Writeln(so:2,' lan  4  = ',so*4:3);
   Writeln(so:2,' lan  5  = ',so*5:3);
   Writeln(so:2,' lan  6  = ',so*6:3);
   Writeln(so:2,' lan  7  = ',so*7:3);
   Writeln(so:2,' lan  8  = ',so*8:3);
   Writeln(so:2,' lan  9  = ',so*9:3);
   Writeln(so:2,' lan 10  = ',so*10:3);
	Readln
End.